# systemctl stop mysql
# systemctl enable mysql
# docker-compose up -d
# docker-compose up --build
# docker container ps -a
# docker logs container_id
# docker-compose down
# docker system prune -a
# docker rmi b7 c1 8e

version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      #- ./db:/docker-entrypoint-initdb.d/
      
